https://zyyttgrfyefxxlgesoke.supabase.co/rest/v1/Temperature?select=*\apikey:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5eXR0Z3JmeWVmeHhsZ2Vzb2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Njg2OTY5NDksImV4cCI6MTk4NDI3Mjk0OX0.Dl7Gfm9KQvATcZyx7KkMffWLbfQC0DrM1KCLglJDM0U\Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5eXR0Z3JmeWVmeHhsZ2Vzb2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Njg2OTY5NDksImV4cCI6MTk4NDI3Mjk0OX0.Dl7Gfm9KQvATcZyx7KkMffWLbfQC0DrM1KCLglJDM0U
